'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import { AnimatePresence } from 'framer-motion';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Oscar Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export function MyApp({ Component, pageProps, router }) {
  return (
    <AnimatePresence mode='wait' initial={false}>
      <Component key={router.pathname} {...pageProps} />
    </AnimatePresence>
  );
}
