import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillGithub, AiFillLinkedin, AiFillInstagram, AiFillMediumCircle} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oscar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>alfa&omega</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className='text-5xl py-2 text-teal-600 font-bold mb-4'>Hi, I'm Oscar</h2>
            <h3 className='text-2xl py-2 font-bold mb-4'>Software developer</h3>
            <p className='text-md py-5 leading-8 mb-4 text-gray-800'>I'm a software engineer based in Santo Domingo, Ecuador. I have a passion for creating beautiful and functional websites and applications. Join me down below and let's get in touch!</p>
          </div>
          <div className="text-3xl flex justify-center gap-8 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillInstagram />
            <AiFillMediumCircle />
          </div>
          <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden">
            <Image className='w-32 h-32 mx-auto my-4' src={deved} alt="emoticon" layout='fill' objectFit='cover' />
          </div>
        </section>
      </main>
    </div>
  );
}
